#!/bin/sh

#check number of arguments
if [ "$#" -ne 3 ]; then
  echo 
  echo "USAGE: $0 assignment-directory src dest"
  echo 
  exit 1
fi

#go to the working directory
cd `dirname $0`
gbdir=`pwd`

#check out whether the folder exists
student_dir="$gbdir/student-work/$1"
if [ ! -d "$student_dir" ]; then
  echo
  echo "Could not open $student_dir"
  echo
  exit 2
fi

#run the grade report
for student in `cat roster`
do
    cd "$student_dir/$1-$student"
    git pull
    cp -Rv $2 $3
    git add -A
    git commit -m "Distributing Handouts"
    git push
    cd $gbdir
done
